server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    I need to specify time zone else there will be a time zone not recognized error
    url: jdbc:mysql://localhost:3306/rest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true